vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        uploaded_pictures:
            uri_prefix: /media/upload
            upload_destination: '%kernel.project_dir%/public/media/upload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
